/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#d5e3fc",
        "on-tertiary-fixed": "#380d00",
        "inverse-surface": "#2d3133",
        "on-surface": "#191c1e",
        "on-primary-fixed-variant": "#00419e",
        "on-secondary-fixed": "#0d1c2e",
        "surface-container-low": "#f2f4f6",
        "on-tertiary": "#ffffff",
        "primary-container": "#1f56b9",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#ffb59b",
        "inverse-on-surface": "#eff1f3",
        "surface-container": "#eceef0",
        "inverse-primary": "#b1c5ff",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dadc",
        "secondary-container": "#d5e3fc",
        "surface-bright": "#f7f9fb",
        "outline": "#737685",
        "primary-fixed": "#dae2ff",
        "on-tertiary-container": "#ffc6b2",
        "on-error-container": "#93000a",
        "surface": "#f7f9fb",
        "tertiary": "#7b2600",
        "surface-tint": "#2559bd",
        "tertiary-container": "#a33500",
        "on-secondary-fixed-variant": "#3a485b",
        "outline-variant": "#c3c6d6",
        "primary": "#003e97",
        "on-background": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b1c5ff",
        "secondary-fixed-dim": "#b9c7df",
        "tertiary-fixed": "#ffdbcf",
        "on-secondary-container": "#57657a",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed-variant": "#812800",
        "secondary": "#515f74",
        "background": "#f7f9fb",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#434654",
        "surface-variant": "#e0e3e5",
        "on-primary-container": "#c3d2ff",
        "on-primary-fixed": "#001946",
        premium: {
          50: '#f8fafc',
          100: '#f1f5f9',
          900: '#0f172a',
        }
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
